---
- hosts: localhost
  become: yes
  tasks:
  - name: create file
    block:
     - file:
         name: /mnt/secret/newfile
         state: touch
    rescue:
      - debug:
          msg: "Unable to create secret file"
